Jenkinsfile
scv-prototype-api/pom.xml
scv-prototype-frontend/.dockerignore
scv-prototype-frontend/Dockerfile
scv-prototype-frontend/package.json
scv-prototype-frontend/src/app/hooks/index.jsx

Update pipeline to build docker images only from master branch. Change docker tagging policy to tag version/master/latest.

Enhanced docker support

---

Jenkinsfile

Added `$VERSION-staging` docker tag

Add environment tagging to Docker image tag

---

scv-prototype-frontend/style-guide.md

Copied style guide from https://github.com/airbnb/javascript/blob/master/react/README.md

Add style-guide.md

---

scv-prototype-frontend/src/index.jsx

Trivial code cleanup. Tested the app locally and navigation still works fine with this bit of code removed.

Remove react-router from index.jsx

---

scv-prototype-frontend/src/app/components/App.jsx
scv-prototype-frontend/src/app/components/Login/Login.jsx
scv-prototype-frontend/src/app/components/Login/Login.test.jsx
scv-prototype-frontend/src/app/components/Login/index.jsx
scv-prototype-frontend/src/app/components/PrivateRoute/PrivateRoute.jsx
scv-prototype-frontend/src/app/components/PrivateRoute/PrivateRoute.test.jsx
scv-prototype-frontend/src/app/components/PrivateRoute/index.jsx
scv-prototype-frontend/src/app/components/ProtectedComponent/ProtectedComponent.jsx
scv-prototype-frontend/src/app/components/ProtectedComponent/index.jsx
scv-prototype-frontend/src/app/components/layout/Main/Header/Header.jsx
scv-prototype-frontend/src/app/components/layout/Main/Header/LoginButton/LoginButton.jsx
scv-prototype-frontend/src/app/components/layout/Main/Header/NavBar/NavBar.jsx
scv-prototype-frontend/src/app/context/AuthContext/AuthContext.jsx
scv-prototype-frontend/src/app/context/AuthContext/AuthProvider.jsx
scv-prototype-frontend/src/app/context/AuthContext/index.jsx
scv-prototype-frontend/src/app/context/index.jsx

**This is a work in progress.**
I've added rudimentary auth routing via the `<PrivateRoute>` component. Currently no authority/role checks are done, and no API calls are made. That functionality will come in a later PR.

Add basic authentication routing

---

Jenkinsfile
scv-prototype-frontend/src/app/App.jsx
scv-prototype-frontend/src/app/components/PrivateRoute/PrivateRoute.jsx
scv-prototype-frontend/src/app/context/AuthContext/AuthContext.jsx
scv-prototype-frontend/src/app/context/AuthContext/AuthProvider.jsx
scv-prototype-frontend/src/app/layout/Main/Header/NavBar/NavBar.jsx
scv-prototype-frontend/src/app/layout/Main/Header/NavBar/NavBarItem/NavBarItem.jsx
scv-prototype-frontend/src/app/views/Login/Login.jsx
scv-prototype-frontend/src/index.jsx

Added a backend call to acquire a JWT token. Mostly works but does have some quirks.
- the AuthContext exposes multiple `setValue(..)` method that cause the components using it to re-render multiple times while updating the context (this should be fixable with a useEffect() call)
- the API endpoint URL is hardcoded
- I used a weird wrapper arrow function in `AuthProvider` to inject the AuthContext values into localstorage ... I'm not sure if this is a good approach
The code does work, though. So there's that.

Add API call to acquire JWT token

---

scv-prototype-frontend/src/app/App.jsx
scv-prototype-frontend/src/app/components/PrivateRoute/PrivateRoute.jsx
scv-prototype-frontend/src/app/context/AuthContext/AuthContext.jsx
scv-prototype-frontend/src/app/context/AuthContext/AuthProvider.jsx
scv-prototype-frontend/src/app/layout/Main/Header/LoginButton/LoginButton.jsx
scv-prototype-frontend/src/app/views/Login/Login.jsx

Changed how the AuthContext stuff works.. Instead of keeping multiple states, a single AuthContext state is stored and loaded.

Refactor the AuthContext stuff

---

scv-prototype-frontend/src/app/services/ApiService.jsx
scv-prototype-frontend/src/app/views/Greeting/Greeting.jsx
scv-prototype-frontend/src/app/views/Login/Login.jsx

Changed promises to async/await syntax as per @sebascomeau's recommendation.

Changed promises to async/await for cleaner code

---

scv-prototype-frontend/src/app/App.jsx
scv-prototype-frontend/src/app/components/PrivateRoute/PrivateRoute.jsx
scv-prototype-frontend/src/app/views/Greeting/Greeting.jsx

Minor tweak to `<PrivateRoute>` component. Works with non-exact routes now.

Fix <PrivateRoute> component to allow nested paths

---

scv-prototype-api/src/main/java/ca/gov/portal/scv/api/config/WebSecurityConfig.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/security/JwtResolver.java

This fix causes the web service to respond with 401 (instead of 403) when unauthenticated.

Respond with 401 when unauthenticated

---

scv-prototype-api/src/dev/resources/application-overrides.yml
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/endpoint/profile/ProfilesController.java
scv-prototype-api/src/main/resources/dummy-data/payment-details.json
scv-prototype-api/src/main/resources/dummy-data/payment-history.json
scv-prototype-api/src/main/resources/dummy-data/profile.json
scv-prototype-api/src/test/java/ca/gov/portal/scv/api/endpoint/profile/ProfilesControllerTests.java
scv-prototype-frontend/src/app/context/Authentication.jsx
scv-prototype-frontend/src/app/hooks/index.jsx
scv-prototype-frontend/src/app/hooks/useApi.jsx
scv-prototype-frontend/src/app/services/ApiService.jsx
scv-prototype-frontend/src/app/views/Greeting/Greeting.jsx
scv-prototype-frontend/src/app/views/Login/Login.jsx
scv-prototype-frontend/src/app/views/Profile/PaymentDetails/Details.jsx
scv-prototype-frontend/src/app/views/Profile/PaymentDetails/PaymentHistory.jsx
scv-prototype-frontend/src/app/views/Profile/ProfileInformation/ProfileInformation.jsx

Added custom `useApi()` hook that can manage authentication state internally.
It works, but I'm getting the following error after login:
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
in Login (at PrivateRoute.jsx:19)
```
Needs investigation.

Experimental custom API hooks

---

scv-prototype-frontend/src/app/components/Button/index.jsx

Format and cleanup of `Button` component to match eslint and prettier configuration.
**No other changes.**

Format Button component

---

scv-prototype-frontend/src/app/components/error/Error403/Error403.jsx
scv-prototype-frontend/src/app/components/error/Error404/Error404.jsx

Clean up of error pages to match eslint and prettier configuration.
**No other changes.**

Clean up error pages

---

scv-prototype-frontend/src/app/i18n/en.json
scv-prototype-frontend/src/app/i18n/fr.json
scv-prototype-frontend/src/app/i18n/index.jsx

Formatted i18n files to be in line with prettier conventions.
**No other changes.**

Format  i18n files

---

scv-prototype-frontend/src/app/App.jsx
scv-prototype-frontend/src/app/utils/api/ApiProvider.jsx
scv-prototype-frontend/src/app/utils/api/ApiService.jsx
scv-prototype-frontend/src/app/utils/api/InvalidTokenError.jsx
scv-prototype-frontend/src/app/utils/api/index.jsx
scv-prototype-frontend/src/app/utils/auth/AuthProvider.jsx
scv-prototype-frontend/src/app/views/Greeting/Greeting.jsx
scv-prototype-frontend/src/app/views/Private.jsx

Refactored the API stuff to follow the same conventions as the Auth stuff.
Right now this is only used on the `Greetings` test page. Will incorporate it into the other components if this is approved.

Refactor API stuff (use on greeting page for now)

---

scv-prototype-frontend/.eslintrc.json
scv-prototype-frontend/.prettierrc.json
scv-prototype-frontend/package-lock.json
scv-prototype-frontend/package.json

Removed .eslintrc and .prettierrc..
Update some dependencies.

Update project configuration

---

scv-prototype-frontend/src/app/App.jsx
scv-prototype-frontend/src/app/components/error/Error403/Error403.jsx
scv-prototype-frontend/src/app/components/error/Error404/Error404.jsx
scv-prototype-frontend/src/app/views/BenefitsServices/BenefitsServices.jsx
scv-prototype-frontend/src/app/views/BookAppointment/BookAppointment.jsx
scv-prototype-frontend/src/app/views/Home/Home.jsx
scv-prototype-frontend/src/app/views/Inbox/Inbox.jsx
scv-prototype-frontend/src/app/views/JobsSkills/JobsSkills.jsx
scv-prototype-frontend/src/app/views/LetsConnect/LetsConnect.jsx
scv-prototype-frontend/src/app/views/Login/Login.jsx
scv-prototype-frontend/src/app/views/Notifications/Notifications.jsx
scv-prototype-frontend/src/app/views/Preferences/Preferences.jsx
scv-prototype-frontend/src/app/views/Profile/Profile.jsx

Updated layout so that the `<MainLayout>` component is now at the page level.
I tested each change and everything appears to work as before.

Move <MainLayout> to each page

---

scv-prototype-api/src/main/java/ca/gov/portal/scv/api/service/dto/AddLocationRequest.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/service/dto/Address.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/service/dto/AddressCategory.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/service/dto/AssociationDateRange.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/service/dto/Country.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/service/dto/Date.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/service/dto/Identification.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/service/dto/Location.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/service/dto/LocationRequest.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/service/dto/Person.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/service/dto/PersonLocationAssociation.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/service/dto/PersonLocationRequest.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/service/dto/PersonRequest.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/service/dto/Program.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/service/dto/ProgramPersonLocationAssociation.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/service/dto/ShareLocationRequest.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/service/dto/State.java

Add some DTO/value-objects that will map to the interop request/response spec.
This is not the entire set of data; just a subset.

Add some interop API value objects

---

scv-prototype-frontend/public/index.html
scv-prototype-frontend/src/app/i18n/en.json
scv-prototype-frontend/src/app/i18n/fr.json
scv-prototype-frontend/src/app/layout/Main/Header/NavMenu.jsx
scv-prototype-frontend/src/app/views/Private/TermsAndConditions/TermsAndConditions.jsx

I think this branch can be merged now?

React native menu toggle

---

.vscode/launch.json
scv-prototype-api/src/dev/resources/application-overrides.yml
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/config/ServiceConfig.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/endpoint/location/LocationsController.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/endpoint/person/PersonController.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/service/InteropService.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/service/InteropServiceImpl.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/service/dto/DateTime.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/service/dto/Person.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/service/dto/PersonLocationsResponse.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/service/dto/PersonName.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/service/dto/PersonProgramsResponse.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/service/dto/PersonResponse.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/service/dto/ProgramBenefitRequest.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/service/dto/ProgramPersonLocationAssociation.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/service/dto/RequestStatus.java
scv-prototype-api/src/main/java/ca/gov/portal/scv/api/service/dto/StatusDate.java
scv-prototype-api/src/main/resources/application.yml
scv-prototype-api/src/test/java/ca/gov/portal/scv/api/endpoint/location/LocationsControllerTest.java
scv-prototype-api/src/test/java/ca/gov/portal/scv/api/endpoint/person/PersonControllerTest.java
scv-prototype-api/src/test/java/ca/gov/portal/scv/api/service/InteropServiceImplIT.java
scv-prototype-api/src/test/resources/application-tests.yml
scv-prototype-frontend/package-lock.json
scv-prototype-frontend/package.json
scv-prototype-frontend/src/app/App.scss
scv-prototype-frontend/src/app/i18n/en.json
scv-prototype-frontend/src/app/i18n/fr.json
scv-prototype-frontend/src/app/views/MSCA.jsx
scv-prototype-frontend/src/app/views/Private/Profile/Addresses/Addresses.jsx

Rebased on latest master commit.. then implement interop person API calls.

Implement interop person API calls

---

scv-prototype-api/src/main/java/ca/gov/portal/scv/api/endpoint/location/LocationsController.java
scv-prototype-api/src/test/java/ca/gov/portal/scv/api/endpoint/location/LocationsControllerTest.java

The controllers do not have to be integration tests. I converted them to unit tests so they execute faster.

Fixed up LocationsController; converted tests to unit tests (were integration tests)

---

scv-prototype-frontend/src/app/i18n/index.jsx
scv-prototype-frontend/src/app/layout/Main/Header/Header.jsx

The language toggle doesn't work (first click) if you clear localstorage and then hit the application. This PR fixes that problem.

Fix language toggle
